"""
Tool: send_email.py
Responsibility: Send the weekly AI report email with PDF attached.
Input:  {"pdf_path": str, "run_date": str, "article_count": int,
          "paper_count": int, "top_keywords": [...], "sheet_url": str}
Output: {"sent": bool, "recipients": [...], "sent_at": str}
"""

import json
import logging
import os
import time
from datetime import datetime, timezone
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

GMAIL_USER = os.environ.get("GMAIL_USER", "")
GMAIL_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD", "")
EMAIL_RECIPIENTS = [
    r.strip()
    for r in os.environ.get("EMAIL_RECIPIENTS", "").split(",")
    if r.strip()
]
MAX_RETRIES = 2


def _build_html_body(run_date: str, article_count: int, paper_count: int,
                      top_keywords: list, sheet_url: str) -> str:
    kw_list = "".join(
        f"<li>{k['keyword']} <span style='color:#E94560'>({k['count']})</span></li>"
        for k in top_keywords[:5]
    )
    sheet_link = (
        f"<a href='{sheet_url}' style='color:#E94560'>View tracking sheet</a>"
        if sheet_url else ""
    )
    return f"""
    <html>
    <body style="background:#1A1A2E;color:#FFFFFF;font-family:Arial,sans-serif;padding:24px;">
      <h1 style="color:#E94560;">AI Research Intelligence Report</h1>
      <h3 style="color:#CCCCCC;">{run_date}</h3>
      <hr style="border-color:#0F3460;">
      <p><strong>News Articles:</strong> {article_count}</p>
      <p><strong>Research Papers:</strong> {paper_count}</p>
      <p><strong>Top Keywords:</strong></p>
      <ul>{kw_list}</ul>
      <p>The full branded PDF report is attached.</p>
      {f'<p>{sheet_link}</p>' if sheet_link else ''}
      <hr style="border-color:#0F3460;">
      <p style="font-size:11px;color:#888;">Auto-generated by AI Research Intelligence System · WAT Framework</p>
    </body>
    </html>
    """


def send_email(
    pdf_path: str,
    run_date: str,
    article_count: int,
    paper_count: int,
    top_keywords: list,
    sheet_url: str = "",
    failure_mode: bool = False,
) -> dict:
    import smtplib

    if not GMAIL_USER or not GMAIL_APP_PASSWORD:
        raise EnvironmentError("GMAIL_USER or GMAIL_APP_PASSWORD not set in environment.")

    if not EMAIL_RECIPIENTS:
        raise EnvironmentError("EMAIL_RECIPIENTS not set in environment.")

    subject = (
        f"[FAILED] AI Research Report — {run_date[:10]}"
        if failure_mode
        else f"AI Research Report — {run_date[:10]}"
    )

    msg = MIMEMultipart("alternative")
    msg["From"] = GMAIL_USER
    msg["To"] = ", ".join(EMAIL_RECIPIENTS)
    msg["Subject"] = subject

    html_body = _build_html_body(run_date, article_count, paper_count, top_keywords, sheet_url)
    msg.attach(MIMEText(html_body, "html"))

    # Attach PDF if it exists
    if pdf_path and os.path.exists(pdf_path):
        with open(pdf_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f'attachment; filename="{os.path.basename(pdf_path)}"',
        )
        msg.attach(part)

    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=15) as server:
                server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
                server.sendmail(GMAIL_USER, EMAIL_RECIPIENTS, msg.as_string())
            sent_at = datetime.now(timezone.utc).isoformat()
            logger.info(f"send_email: delivered to {EMAIL_RECIPIENTS}")
            return {
                "sent": True,
                "recipients": EMAIL_RECIPIENTS,
                "sent_at": sent_at,
            }
        except Exception as e:
            last_error = e
            logger.warning(f"send_email attempt {attempt}/{MAX_RETRIES} failed: {e}")
            if attempt < MAX_RETRIES:
                time.sleep(5)

    logger.error(f"send_email failed after {MAX_RETRIES} attempts: {last_error}")
    return {
        "sent": False,
        "recipients": EMAIL_RECIPIENTS,
        "sent_at": "",
        "error": str(last_error),
    }


if __name__ == "__main__":
    import sys
    payload = json.loads(sys.stdin.read()) if not sys.stdin.isatty() else {}
    output = send_email(
        pdf_path=payload.get("pdf_path", ""),
        run_date=payload.get("run_date", datetime.now().isoformat()),
        article_count=payload.get("article_count", 0),
        paper_count=payload.get("paper_count", 0),
        top_keywords=payload.get("top_keywords", []),
        sheet_url=payload.get("sheet_url", ""),
    )
    print(json.dumps(output, indent=2))
